# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('under_review', 'In Prüfung'), ('ended', 'Beendet')], default='active', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('data_categories', models.TextField(blank=True)),
                ('data_subject_groups', models.TextField(blank=True)),
                ('server_locations', models.TextField(blank=True)),
                ('third_country_transfer', models.BooleanField(default=False)),
                ('third_country_description', models.TextField(blank=True)),
                ('subprocessors_used', models.BooleanField(default=False)),
                ('av_contract_exists', models.BooleanField(default=False)),
                ('contract_valid_from', models.DateField(blank=True, null=True)),
                ('contract_valid_until', models.DateField(blank=True, null=True)),
                ('tom_exists', models.BooleanField(default=False)),
                ('certifications', models.TextField(blank=True)),
                ('risk_class', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=20)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
