# Generated by Django 5.2.12 on 2026-04-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0002_alter_processor_options_processor_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('default_contact_person', models.CharField(blank=True, max_length=255)),
                ('default_contact_email', models.EmailField(blank=True, max_length=254)),
                ('standard_av_available', models.BooleanField(default=False)),
                ('standard_tom_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anbieterkatalogeintrag',
                'verbose_name_plural': 'Anbieterkatalogeinträge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Anbieterrolle',
                'verbose_name_plural': 'Anbieterrollen',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['name'], 'verbose_name': 'Auftragsverarbeiter', 'verbose_name_plural': 'Auftragsverarbeiter'},
        ),
        migrations.AddField(
            model_name='processor',
            name='custom_provider_role',
            field=models.CharField(blank=True, help_text='Zusätzliche freie Rollenbezeichnung, falls keine Standardrolle passt.', max_length=255, verbose_name='Eigene / abweichende Rolle'),
        ),
        migrations.AddField(
            model_name='processor',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processors', to='processors.providercatalogentry', verbose_name='Bekannter Anbieter'),
        ),
        migrations.AddField(
            model_name='providercatalogentry',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='catalog_entries', to='processors.providerrole'),
        ),
        migrations.AddField(
            model_name='processor',
            name='provider_roles',
            field=models.ManyToManyField(blank=True, related_name='processors', to='processors.providerrole', verbose_name='AV-Rollen'),
        ),
    ]
