# Generated by Django 5.2.12 on 2026-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0003_providercatalogentry_providerrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercatalogentry',
            name='standard_av_file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/av/', verbose_name='Standard-AV (Datei)'),
        ),
        migrations.AddField(
            model_name='providercatalogentry',
            name='standard_tom_file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/tom/', verbose_name='Standard-TOM (Datei)'),
        ),
    ]
