# Generated by Django 5.2.12 on 2026-03-16 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('legal_guidance', 'Rechtliche Leitlinie'), ('dpia_guidance', 'DSFA-Leitlinie'), ('assessment_scheme', 'Bewertungsschema'), ('internal_policy', 'Interne Richtlinie'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Textinhalt für die KI-Auswertung. Kann zusätzlich oder alternativ zur Datei gepflegt werden.')),
                ('source_note', models.CharField(blank=True, help_text="Interne Quelle oder Kurzvermerk, z. B. 'Kanzleistandard 2026'.", max_length=255)),
                ('file', models.FileField(blank=True, help_text='Erlaubte Formate: txt, md, docx, pdf', null=True, upload_to='knowledge/entries/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'md', 'docx', 'pdf'])])),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_for_ai', models.BooleanField(default=True, help_text='Die KI darf diesen Eintrag verwenden.')),
                ('admin_only', models.BooleanField(default=True, help_text='Nur Admin sichtbar.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wissenseintrag',
                'verbose_name_plural': 'Wissenseinträge',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('data_subject_rights', 'Betroffenenrechte'), ('data_breach', 'Datenschutzvorfall'), ('internal_request', 'Interne Anfrage'), ('processor_request', 'Anfrage an Auftragsverarbeiter'), ('dpia', 'DSFA'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_text', models.TextField(blank=True, help_text='Mustertext für die KI oder für spätere manuelle Nutzung.')),
                ('file', models.FileField(blank=True, help_text='Erlaubte Formate: txt, md, docx, pdf', null=True, upload_to='knowledge/templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'md', 'docx', 'pdf'])])),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_for_ai', models.BooleanField(default=True, help_text='Die KI darf diesen Mustertext verwenden.')),
                ('admin_only', models.BooleanField(default=True, help_text='Nur Admin sichtbar.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mustertext',
                'verbose_name_plural': 'Mustertexte',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrustedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('supervisory_authority', 'Aufsichtsbehörde'), ('public_guidance', 'Öffentliche Leitlinie'), ('legislation', 'Gesetzgebung'), ('court', 'Gericht / Rechtsprechung'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('base_url', models.URLField(help_text='Nur von dir freigegebene offizielle Quelle.', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_for_ai', models.BooleanField(default=True, help_text='Die KI darf diese Quelle ergänzend verwenden.')),
                ('admin_only', models.BooleanField(default=True, help_text='Nur Admin sichtbar.')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Niedriger Wert = höhere Priorität.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vertrauenswürdige Quelle',
                'verbose_name_plural': 'Vertrauenswürdige Quellen',
                'ordering': ['priority', 'title'],
            },
        ),
    ]
