# Generated by Django 5.2.12 on 2026-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('legitimate_interest', 'Interessenabwägung'), ('dpia', 'DSFA'), ('legal_assessment', 'Rechtsbewertung'), ('template', 'Mustertext'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('raw_text', models.TextField(help_text='Rohtext für interne Analyse und KI-Auswertung.')),
                ('ai_enabled', models.BooleanField(default=True, help_text='Die KI darf diesen Text bei themenbezogenen Auswertungen verwenden.')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysetext',
                'verbose_name_plural': 'Analysetexte',
                'ordering': ['topic', 'title'],
            },
        ),
    ]
