# Generated by Django 5.2.12 on 2026-04-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_analysetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wissensordner',
                'verbose_name_plural': 'Wissensordner',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='analysetext',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyse_texts', to='knowledge.knowledgefolder'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='knowledge.knowledgefolder'),
        ),
        migrations.AddField(
            model_name='texttemplate',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_templates', to='knowledge.knowledgefolder'),
        ),
        migrations.AddField(
            model_name='trustedsource',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trusted_sources', to='knowledge.knowledgefolder'),
        ),
    ]
