# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_basis_art6', models.CharField(choices=[('consent', 'Art. 6 Abs. 1 lit. a DSGVO'), ('contract', 'Art. 6 Abs. 1 lit. b DSGVO'), ('legal_obligation', 'Art. 6 Abs. 1 lit. c DSGVO'), ('vital_interests', 'Art. 6 Abs. 1 lit. d DSGVO'), ('public_task', 'Art. 6 Abs. 1 lit. e DSGVO'), ('legitimate_interest', 'Art. 6 Abs. 1 lit. f DSGVO')], max_length=50)),
                ('legal_basis_art9', models.CharField(blank=True, max_length=255)),
                ('consent_required', models.BooleanField(default=False)),
                ('legal_obligation_exists', models.BooleanField(default=False)),
                ('legitimate_interest_used', models.BooleanField(default=False)),
                ('legal_basis_reasoning', models.TextField()),
                ('necessity_description', models.TextField(blank=True)),
                ('data_minimisation_checked', models.BooleanField(default=False)),
                ('transparency_checked', models.BooleanField(default=False)),
                ('retention_concept_checked', models.BooleanField(default=False)),
                ('third_country_checked', models.BooleanField(default=False)),
                ('overall_assessment', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('permitted', 'Zulässig'), ('permitted_with_clarification', 'Zulässig mit Klärungsbedarf'), ('not_approved', 'Nicht freigegeben')], max_length=50)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_assessment', to='processing.processingactivity')),
            ],
        ),
    ]
