# Generated by Django 5.2.12 on 2026-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalassessment',
            name='professional_secrecy',
            field=models.BooleanField(default=False, help_text='Berufsgeheimnis / § 203 StGB relevant'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legalassessment',
            name='legal_basis_art6',
            field=models.CharField(blank=True, choices=[('consent', 'Art. 6 Abs. 1 lit. a DSGVO'), ('contract', 'Art. 6 Abs. 1 lit. b DSGVO'), ('legal_obligation', 'Art. 6 Abs. 1 lit. c DSGVO'), ('vital_interests', 'Art. 6 Abs. 1 lit. d DSGVO'), ('public_task', 'Art. 6 Abs. 1 lit. e DSGVO'), ('legitimate_interest', 'Art. 6 Abs. 1 lit. f DSGVO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legalassessment',
            name='legal_basis_art9',
            field=models.CharField(blank=True, choices=[('', 'Keine besondere Kategorie'), ('explicit_consent', 'Art. 9 Abs. 2 lit. a DSGVO'), ('employment_social_security', 'Art. 9 Abs. 2 lit. b DSGVO'), ('vital_interests', 'Art. 9 Abs. 2 lit. c DSGVO'), ('not_for_profit', 'Art. 9 Abs. 2 lit. d DSGVO'), ('made_public', 'Art. 9 Abs. 2 lit. e DSGVO'), ('legal_claims', 'Art. 9 Abs. 2 lit. f DSGVO'), ('substantial_public_interest', 'Art. 9 Abs. 2 lit. g DSGVO'), ('health_social_care', 'Art. 9 Abs. 2 lit. h DSGVO'), ('public_health', 'Art. 9 Abs. 2 lit. i DSGVO'), ('archiving_research_statistics', 'Art. 9 Abs. 2 lit. j DSGVO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legalassessment',
            name='legal_basis_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='legalassessment',
            name='result',
            field=models.CharField(choices=[('permitted', 'Zulässig'), ('permitted_with_clarification', 'Zulässig mit Klärungsbedarf'), ('not_approved', 'Nicht freigegeben')], default='permitted_with_clarification', max_length=50),
        ),
    ]
