# Generated by Django 5.2.12 on 2026-03-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('legal', '0002_legalassessment_professional_secrecy_and_more'),
        ('processing', '0006_remove_processingactivity_legal_assessment_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalassessment',
            options={'ordering': ['processing_activity__title']},
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='consent_required',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='data_minimisation_checked',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='legal_basis_art6',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='legal_basis_art9',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='legal_basis_reasoning',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='legal_obligation_exists',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='legitimate_interest_used',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='necessity_description',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='overall_assessment',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='result',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='retention_concept_checked',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='reviewer_name',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='third_country_checked',
        ),
        migrations.RemoveField(
            model_name='legalassessment',
            name='transparency_checked',
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='dpia_required',
            field=models.BooleanField(default=False, help_text='DSFA erforderlich'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legal_assessment_text',
            field=models.TextField(blank=True, help_text='Juristische Bewertung / Begründung'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legal_basis',
            field=models.CharField(blank=True, choices=[('consent', 'Art. 6 Abs. 1 lit. a DSGVO – Einwilligung'), ('contract', 'Art. 6 Abs. 1 lit. b DSGVO – Vertrag / vorvertragliche Maßnahmen'), ('legal_obligation', 'Art. 6 Abs. 1 lit. c DSGVO – Rechtliche Verpflichtung'), ('vital_interests', 'Art. 6 Abs. 1 lit. d DSGVO – Lebenswichtige Interessen'), ('public_task', 'Art. 6 Abs. 1 lit. e DSGVO – Öffentliche Aufgabe'), ('legitimate_interests', 'Art. 6 Abs. 1 lit. f DSGVO – Berechtigtes Interesse')], max_length=50),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legitimate_interest_test',
            field=models.BooleanField(default=False, help_text='Interessenabwägung erforderlich'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='open_issues',
            field=models.TextField(blank=True, help_text='Offene Rechtsfragen / Klärungspunkte'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='special_legal_basis',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('employment', 'Art. 9 Abs. 2 lit. b DSGVO – Arbeitsrecht / Sozialrecht'), ('vital', 'Art. 9 Abs. 2 lit. c DSGVO – Lebenswichtige Interessen'), ('legal_claims', 'Art. 9 Abs. 2 lit. f DSGVO – Rechtsansprüche'), ('medical', 'Art. 9 Abs. 2 lit. h DSGVO – Medizinische Behandlung'), ('public_health', 'Art. 9 Abs. 2 lit. i DSGVO – Öffentliches Gesundheitsinteresse'), ('explicit_consent', 'Art. 9 Abs. 2 lit. a DSGVO – Ausdrückliche Einwilligung')], max_length=50),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='legalassessment',
            name='processing_activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_record', to='processing.processingactivity'),
        ),
    ]
