# Generated by Django 5.2.12 on 2026-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_alter_legalassessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalassessment',
            name='ai_last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='ai_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='ai_prompt_version',
            field=models.CharField(blank=True, default='v1', max_length=50),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='ai_suggestion',
            field=models.TextField(blank=True),
        ),
    ]
