# Generated by Django 5.2.12 on 2026-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_legalassessment_ai_last_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalassessment',
            name='data_subject_impact',
            field=models.TextField(blank=True, help_text='Welche Auswirkungen oder Risiken bestehen für die betroffene Person?'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legitimate_interest_completed',
            field=models.BooleanField(default=False, help_text='Interessenabwägung inhaltlich abgeschlossen.'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legitimate_interest_outcome',
            field=models.CharField(blank=True, choices=[('controller', 'Interessen des Verantwortlichen überwiegen'), ('balanced', 'Abwägung ausgeglichen / vertretbar'), ('data_subject', 'Interessen der betroffenen Person überwiegen')], max_length=30),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legitimate_interest_purpose',
            field=models.TextField(blank=True, help_text='Welches berechtigte Interesse verfolgt der Verantwortliche?'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='legitimate_interest_reasoning',
            field=models.TextField(blank=True, help_text='Zusammenfassende Begründung der Interessenabwägung.'),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='safeguards',
            field=models.TextField(blank=True, help_text='Welche Schutzmaßnahmen sprechen zugunsten der Zulässigkeit?'),
        ),
    ]
