# Generated by Django 5.2.12 on 2026-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_legalassessment_data_subject_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalassessment',
            name='legitimate_interest_test',
            field=models.BooleanField(default=False, help_text='Interessenabwägung durchgeführt'),
        ),
    ]
