# Generated by Django 5.2.12 on 2026-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_alter_legalassessment_legitimate_interest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalassessment',
            name='dpia_required',
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='no_dpia_check_required_note',
            field=models.TextField(blank=True, help_text="Ergänzende Begründung, insbesondere bei 'Sonstiger Grund'."),
        ),
        migrations.AddField(
            model_name='legalassessment',
            name='no_dpia_check_required_reason',
            field=models.CharField(blank=True, choices=[('', 'Bitte auswählen'), ('not_relevant_as_such', 'Verfahren als solches nicht DSFA-relevant'), ('not_relevant_by_discretion', 'Verfahren nach ausgeübtem Ermessen nicht DSFA-relevant'), ('no_high_risk', 'Kein hohes Risiko für Rechte und Freiheiten erkennbar'), ('no_must_list_case', 'Kein Muss-Listen-Fall / kein typischer Hochrisikofall'), ('other', 'Sonstiger Grund')], help_text='Dokumentation, warum kein gesonderter DSFA-Check erforderlich ist.', max_length=50),
        ),
    ]
