# Generated by Django 5.2.12 on 2026-04-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0007_remove_legalassessment_dpia_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalassessment',
            name='section_203_process_implemented',
            field=models.BooleanField(default=False, help_text='203er Verfahren für dieses Verfahren implementiert und dokumentiert'),
        ),
    ]
