# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('responsible_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('systems_used', models.TextField(blank=True)),
                ('data_subject_categories', models.TextField(blank=True)),
                ('personal_data_categories', models.TextField(blank=True)),
                ('special_category_data', models.BooleanField(default=False)),
                ('special_category_description', models.TextField(blank=True)),
                ('recipients', models.TextField(blank=True)),
                ('third_country_transfer', models.BooleanField(default=False)),
                ('third_country_description', models.TextField(blank=True)),
                ('retention_period', models.CharField(blank=True, max_length=255)),
                ('tom_summary', models.TextField(blank=True)),
                ('dpia_required', models.BooleanField(default=False)),
                ('dpia_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processing_activities', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processing.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_processing_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['internal_id'],
            },
        ),
    ]
