# Generated by Django 5.2.12 on 2026-03-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processingactivity_options_department_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('data_subject_categories', models.TextField(blank=True)),
                ('personal_data_categories', models.TextField(blank=True)),
                ('recipients', models.TextField(blank=True)),
                ('retention_period', models.CharField(blank=True, max_length=255)),
                ('tom_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='processingactivity',
            options={'ordering': ['internal_id', 'title']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='responsible_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.department'),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='internal_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('review', 'In Prüfung'), ('archived', 'Archiviert')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingactivity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
