# Generated by Django 5.2.12 on 2026-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_processingtemplate_alter_processingactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingtemplate',
            options={'ordering': ['template_group', 'title']},
        ),
        migrations.AddField(
            model_name='processingtemplate',
            name='template_group',
            field=models.CharField(choices=[('general', 'Allgemein'), ('medical', 'Arztpraxis'), ('legal', 'Rechtsanwaltskanzlei')], default='general', max_length=20),
        ),
    ]
