# Generated by Django 5.2.12 on 2026-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_processingtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='legal_assessment_text',
            field=models.TextField(blank=True, help_text='Juristische Bewertung / Begründung'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='legal_basis',
            field=models.CharField(blank=True, help_text='Rechtsgrundlage nach Art. 6 DSGVO', max_length=100),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='professional_secrecy',
            field=models.BooleanField(default=False, help_text='Berufsgeheimnis / § 203 StGB relevant'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='risk_level',
            field=models.CharField(blank=True, help_text='Risikoeinstufung (niedrig / mittel / hoch)', max_length=50),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='special_legal_basis',
            field=models.CharField(blank=True, help_text='Rechtsgrundlage nach Art. 9 DSGVO', max_length=100),
        ),
    ]
