# Generated by Django 5.2.12 on 2026-03-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingactivity',
            name='legal_assessment_text',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='legal_basis',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='professional_secrecy',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='special_legal_basis',
        ),
    ]
