# Generated by Django 5.2.12 on 2026-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_remove_processingactivity_legal_assessment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingactivity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='reminder_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='review_status',
            field=models.CharField(choices=[('not_started', 'Noch nicht bewertet'), ('in_progress', 'Bewertung begonnen'), ('completed', 'Abgeschlossen')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='third_party_info_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='third_party_info_required',
            field=models.BooleanField(default=False),
        ),
    ]
