# Generated by Django 5.2.12 on 2026-03-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_review_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingactivity',
            name='review_status',
            field=models.CharField(choices=[('not_started', 'Noch nicht bewertet'), ('in_progress', 'Bewertung begonnen'), ('completed', 'Abgeschlossen')], default='not_started', max_length=20),
        ),
    ]
