# Generated by Django 5.2.12 on 2026-03-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_alter_processingactivity_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingactivity',
            name='dpia_completed',
        ),
        migrations.RemoveField(
            model_name='processingactivity',
            name='dpia_required',
        ),
    ]
