# Generated by Django 5.2.12 on 2026-03-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_remove_processingactivity_dpia_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStandardCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('hr', 'Personal / Organisation'), ('core_process', 'Fachprozess / Kerntätigkeit'), ('communication', 'Kommunikation / Zusammenarbeit'), ('it_security', 'IT / Sicherheit'), ('monitoring', 'Überwachung / Tracking'), ('data_transfer', 'Datenflüsse / Externe'), ('analytics', 'Analyse / Bewertung'), ('special', 'Spezialfall')], default='general', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_general', models.BooleanField(default=True, help_text='Allgemeiner Standardfall, der branchenübergreifend angezeigt werden kann.')),
                ('applies_to_legal', models.BooleanField(default=False)),
                ('applies_to_medical', models.BooleanField(default=False)),
                ('applies_to_industry', models.BooleanField(default=False)),
                ('risk_hint', models.CharField(blank=True, choices=[('low', 'Eher niedrig'), ('medium', 'Eher mittel'), ('high', 'Eher hoch')], help_text='Unverbindliche Risikotendenz für die erste Einordnung.', max_length=20)),
                ('dsfa_relevance_note', models.TextField(blank=True, help_text='Interner Hinweis zur DSFA-Relevanz oder typischen Einordnung.')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standardfall',
                'verbose_name_plural': 'Standardfälle',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='standard_case_note',
            field=models.TextField(blank=True, help_text='Optionale Konkretisierung oder Ergänzung zum gewählten Standardfall.'),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='standard_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_activities', to='processing.processingstandardcase'),
        ),
    ]
