# Generated by Django 5.2.12 on 2026-03-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('processing', '0011_processingstandardcase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingstandardcase',
            options={'ordering': ['name'], 'verbose_name': 'Standardfall', 'verbose_name_plural': 'Standardfälle'},
        ),
        migrations.AlterModelOptions(
            name='processingtemplate',
            options={'ordering': ['template_group', 'title'], 'verbose_name': 'Verfahrensvorlage', 'verbose_name_plural': 'Verfahrensvorlagen'},
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='template_origin',
            field=models.ForeignKey(blank=True, help_text='Optionale Herkunft aus einer Verfahrensvorlage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_processing_activities', to='processing.processingtemplate'),
        ),
        migrations.CreateModel(
            name='TenantProcessingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_links', to='processing.processingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_template_links', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Mandanten-Verfahrensvorlage',
                'verbose_name_plural': 'Mandanten-Verfahrensvorlagen',
                'ordering': ['tenant__name', 'sort_order', 'template__title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'template'), name='unique_tenant_processing_template')],
            },
        ),
    ]
