# Generated by Django 5.2.12 on 2026-03-30 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('processing', '0012_alter_processingstandardcase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processingactivity',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingactivity',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TenantProcessingTemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='processing.processingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_settings', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Mandanten-Vorlagensteuerung',
                'verbose_name_plural': 'Mandanten-Vorlagensteuerungen',
                'ordering': ['template__title'],
                'unique_together': {('tenant', 'template')},
            },
        ),
        migrations.DeleteModel(
            name='TenantProcessingTemplate',
        ),
    ]
