# Generated by Django 5.2.12 on 2026-06-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_processingactivity_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionDataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('technical_key', models.SlugField(help_text='Stabile technische ID für Excel-/Seed-Import, z. B. email_handelsbrief.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Löschobjekt',
                'verbose_name_plural': 'Löschobjekte',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RetentionStorageSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('technical_key', models.SlugField(help_text='Stabile technische ID für Excel-/Seed-Import, z. B. outlook_exchange.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_deletion_location', models.CharField(blank=True, help_text='Typischer Löschort, z. B. Postfach, Archiv, Fachsoftware.', max_length=255)),
                ('default_information_owner', models.CharField(blank=True, help_text='Typische Rolle, z. B. Verwaltung, Buchhaltung, Mandatsverantwortlicher.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System / Speicherort',
                'verbose_name_plural': 'Systeme / Speicherorte',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_key', models.SlugField(help_text='Stabile technische ID für Excel-/Seed-Import, z. B. rule_email_handelsbrief_outlook.', max_length=160, unique=True)),
                ('retention_period_value', models.PositiveIntegerField(blank=True, help_text="Zahl der Frist, z. B. 6 oder 10. Leer bei 'unverzüglich' oder 'prüfen'.", null=True)),
                ('retention_period_unit', models.CharField(choices=[('immediate', 'unverzüglich'), ('days', 'Tage'), ('weeks', 'Wochen'), ('months', 'Monate'), ('years', 'Jahre'), ('check', 'prüfen')], default='check', max_length=30)),
                ('trigger', models.CharField(blank=True, help_text='Startzeitpunkt der Frist, z. B. Jahresende, Vertragsende, Zweckfortfall.', max_length=255)),
                ('legal_basis', models.CharField(blank=True, help_text='Rechtsgrund / Hinweis, z. B. HGB, AO, BRAO, DSGVO.', max_length=255)),
                ('rule_type', models.CharField(choices=[('legal_retention', 'gesetzliche Aufbewahrung'), ('legal_deletion', 'gesetzliche Löschung'), ('purpose_end', 'Zweckfortfall'), ('consent_withdrawal', 'Widerruf / Einwilligung'), ('limitation', 'Verjährungsorientierung'), ('organisational', 'Organisationsentscheidung'), ('check_required', 'Einzelfallprüfung')], default='check_required', max_length=40)),
                ('deletion_location', models.CharField(blank=True, help_text='Konkreter Löschort, z. B. Postfach/Archiv, DATEV, Fachsoftware.', max_length=255)),
                ('information_owner_role', models.CharField(blank=True, help_text='Typischer Informationsinhaber / zuständige Rolle.', max_length=255)),
                ('requires_review', models.BooleanField(default=False, help_text='Markiert Regeln, die fachlich geprüft werden müssen.')),
                ('is_na_rule', models.BooleanField(default=False, help_text='Markiert Fälle, in denen kein Löschkonzept erforderlich ist.')),
                ('note', models.TextField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_rules', to='processing.retentiondataobject')),
                ('storage_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_rules', to='processing.retentionstoragesystem')),
            ],
            options={
                'verbose_name': 'Löschregel',
                'verbose_name_plural': 'Löschregeln',
                'ordering': ['sort_order', 'data_object__name', 'storage_system__name'],
                'unique_together': {('data_object', 'storage_system')},
            },
        ),
    ]
