# Generated by Django 5.2.12 on 2026-07-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0015_retention_stabilization (1)'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retentiondataobject',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Aufbewahrungstatbestand', 'verbose_name_plural': 'Aufbewahrungstatbestände'},
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='legal_basis',
            field=models.CharField(blank=True, help_text='Rechtsgrundlage oder interner Quellenhinweis, z. B. HGB, AO, BGB, MiLoG, BRAO.', max_length=255, verbose_name='Rechtsgrundlage / Quelle'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='retention_period_unit',
            field=models.CharField(choices=[('immediate', 'unverzüglich'), ('days', 'Tage'), ('weeks', 'Wochen'), ('months', 'Monate'), ('years', 'Jahre'), ('check', 'prüfen')], default='check', max_length=30, verbose_name='Fristeinheit'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='retention_period_value',
            field=models.PositiveIntegerField(blank=True, help_text="Zahl der Frist, z. B. 3, 6 oder 10. Leer bei 'prüfen' oder 'unverzüglich'.", null=True, verbose_name='Standardfrist'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='retention_trigger',
            field=models.CharField(blank=True, help_text='Startzeitpunkt der Frist, z. B. Jahresende, Vertragsende, Ausscheiden, Behandlungsende.', max_length=255, verbose_name='Fristbeginn / Auslöser'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='review_note',
            field=models.TextField(blank=True, help_text='Hinweis für DSB, Audit, Revision oder WP, z. B. Vertragsende prüfen, Handelsbriefe abgrenzen.', verbose_name='Prüfhinweis'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='review_status',
            field=models.CharField(choices=[('automatic', 'automatisch anwendbar'), ('check', 'fachlich prüfen'), ('legal_review', 'juristisch / Audit prüfen')], default='check', help_text='Gibt an, ob der Tatbestand automatisch nutzbar ist oder fachlich/juristisch geprüft werden muss.', max_length=30, verbose_name='Prüfstatus'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='typical_personal_data_categories',
            field=models.TextField(blank=True, help_text='Typische pbD / Datenkategorien, z. B. Namensdaten, Kontaktdaten, Rechnungsdaten, Beschäftigtendaten. Diese Angaben können später in das Verfahren übernommen und dort ergänzt werden.', verbose_name='Typische personenbezogene Daten'),
        ),
        migrations.AddField(
            model_name='retentiondataobject',
            name='typical_storage_locations',
            field=models.TextField(blank=True, help_text='Optionale Orientierung aus der Stammdaten-/Excel-Liste, z. B. E-Mail-System, DMS, ERP, Papierakte. Die konkreten Löschorte werden später im Verfahren ausgewählt.', verbose_name='Typische Löschorte'),
        ),
        migrations.AlterField(
            model_name='retentiondataobject',
            name='description',
            field=models.TextField(blank=True, help_text='Fachliche Beschreibung des Aufbewahrungstatbestands.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='retentiondataobject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Aufbewahrungstatbestand'),
        ),
        migrations.CreateModel(
            name='RetentionStorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Konkrete Bezeichnung, z. B. Outlook / Exchange, RA-MICRO, SAP, Kellerarchiv, NAS01.', max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Kann später genutzt werden, um typische Löschorte bei neuen Verfahren vorzuschlagen.', verbose_name='Standard für neue Verfahren')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='processing.retentionstoragesystem', verbose_name='Löschort-Typ')),
            ],
            options={
                'verbose_name': 'Löschort / System',
                'verbose_name_plural': 'Löschorte / Systeme',
                'ordering': ['storage_system__sort_order', 'sort_order', 'name'],
                'unique_together': {('storage_system', 'name')},
            },
        ),
    ]
