# Generated by Django 5.2.12 on 2026-07-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0016_alter_retentiondataobject_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retentionrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retentionrule',
            name='data_object',
        ),
        migrations.RemoveField(
            model_name='retentionrule',
            name='storage_system',
        ),
        migrations.AlterModelOptions(
            name='processingretentionassignment',
            options={'ordering': ['processing_activity', 'sort_order', 'data_object__name'], 'verbose_name': 'Aufbewahrungstatbestand im Verfahren', 'verbose_name_plural': 'Aufbewahrungstatbestände in Verfahren'},
        ),
        migrations.AlterModelOptions(
            name='retentionstoragesystem',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Löschort / System', 'verbose_name_plural': 'Löschorte / Systeme'},
        ),
        migrations.AlterUniqueTogether(
            name='processingretentionassignment',
            unique_together={('processing_activity', 'data_object')},
        ),
        migrations.AddField(
            model_name='processingretentionassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='processingretentionassignment',
            name='custom_note',
            field=models.TextField(blank=True, help_text='Optionale Konkretisierung oder Abweichung im konkreten Verfahren.', verbose_name='Hinweis zum Verfahren'),
        ),
        migrations.AlterField(
            model_name='processingretentionassignment',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_assignments', to='processing.retentiondataobject', verbose_name='Aufbewahrungstatbestand'),
        ),
        migrations.AlterField(
            model_name='processingretentionassignment',
            name='processing_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_assignments', to='processing.processingactivity', verbose_name='Verfahren'),
        ),
        migrations.CreateModel(
            name='ProcessingStorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_note', models.CharField(blank=True, help_text='Optionaler Freitext, z. B. konkrete Produktbezeichnung, Servername, Archivraum oder sonstige Konkretisierung.', max_length=255, verbose_name='Ergänzende Bezeichnung / Hinweis')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='processing.processingactivity', verbose_name='Verfahren')),
                ('storage_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_assignments', to='processing.retentionstoragesystem', verbose_name='Löschort / System')),
            ],
            options={
                'verbose_name': 'Löschort / System im Verfahren',
                'verbose_name_plural': 'Löschorte / Systeme in Verfahren',
                'ordering': ['processing_activity', 'sort_order', 'storage_system__name'],
                'unique_together': {('processing_activity', 'storage_system')},
            },
        ),
        migrations.DeleteModel(
            name='RetentionStorageLocation',
        ),
        migrations.RemoveField(
            model_name='processingretentionassignment',
            name='applied_rule',
        ),
        migrations.RemoveField(
            model_name='processingretentionassignment',
            name='na_reason',
        ),
        migrations.RemoveField(
            model_name='processingretentionassignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='processingretentionassignment',
            name='storage_system',
        ),
        migrations.DeleteModel(
            name='RetentionRule',
        ),
    ]
