# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('legal', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('audit', 'Audit'), ('processing', 'Verarbeitungsvorgang'), ('legal_assessment', 'Rechtliche Bewertung')], max_length=30)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('completed', 'Erledigt'), ('discarded', 'Verworfen')], default='open', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('effectiveness_review', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audits.audit')),
                ('related_legal_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal.legalassessment')),
                ('related_processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processing.processingactivity')),
            ],
            options={
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
