# Generated by Django 5.2.12 on 2026-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={},
        ),
        migrations.AddField(
            model_name='actionitem',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('waiting', 'Wartet auf Rückmeldung'), ('follow_up', 'Wiedervorlage'), ('completed', 'Erledigt'), ('discarded', 'Verworfen')], default='open', max_length=20),
        ),
    ]
