# Generated by Django 5.2.12 on 2026-03-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('actions', '0002_alter_actionitem_options_actionitem_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
    ]
