# Generated by Django 5.2.12 on 2026-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_actionitem_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='source_area',
            field=models.CharField(choices=[('processing', 'Verfahren'), ('legal', 'Rechtsbewertung'), ('dpia', 'DSFA'), ('audit', 'Audit'), ('document', 'Dokument'), ('report', 'Report'), ('request', 'Anfrage'), ('manual', 'Manuell')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='target_area',
            field=models.CharField(choices=[('processing', 'Verfahren'), ('legal', 'Rechtsbewertung'), ('dpia', 'DSFA'), ('audit', 'Audit'), ('document', 'Dokument'), ('report', 'Report'), ('request', 'Anfrage'), ('manual', 'Manuell')], default='processing', max_length=20),
        ),
    ]
