# Generated by Django 5.2.12 on 2026-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_actionitem_source_area_actionitem_target_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='source_type',
            field=models.CharField(choices=[('audit', 'Audit'), ('processing', 'Verarbeitungsvorgang'), ('legal_assessment', 'Rechtliche Bewertung'), ('dpia', 'DSFA')], max_length=30),
        ),
    ]
