# Generated by Django 5.2.12 on 2026-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_actionitem_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('waiting', 'Wartet auf Rückmeldung'), ('follow_up', 'Wiedervorlage'), ('completed', 'Erledigt'), ('irrelevant', 'Gegenstandslos'), ('discarded', 'Verworfen')], default='open', max_length=20),
        ),
    ]
