# Generated by Django 5.2.12 on 2026-04-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_actionitem_status'),
        ('audits', '0003_procedureaudit_procedureaudititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='related_procedure_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audits.procedureaudit'),
        ),
    ]
