# Generated by Django 5.2.12 on 2026-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_actionitem_related_procedure_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='audit_section',
            field=models.CharField(blank=True, choices=[('', 'Kein Auditabschnitt'), ('procedure_review', 'Verfahrensprüfung'), ('new_activities', 'Neue Verfahren'), ('general_review', 'Allgemeine Prüfung')], default='', max_length=30),
        ),
    ]
