# Generated by Django 5.2.12 on 2026-04-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_actionitem_audit_section'),
        ('processors', '0004_providercatalogentry_standard_av_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['status', '-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='actionitem',
            name='related_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='processors.processor'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='source_area',
            field=models.CharField(choices=[('processing', 'Verfahren'), ('legal', 'Rechtsbewertung'), ('dpia', 'DSFA'), ('audit', 'Audit'), ('document', 'Dokument'), ('report', 'Report'), ('request', 'Anfrage'), ('manual', 'Manuell'), ('processor', 'Auftragsverarbeiter')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='source_type',
            field=models.CharField(choices=[('audit', 'Audit'), ('processing', 'Verarbeitungsvorgang'), ('legal_assessment', 'Rechtliche Bewertung'), ('dpia', 'DSFA'), ('processor', 'Auftragsverarbeiter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='target_area',
            field=models.CharField(choices=[('processing', 'Verfahren'), ('legal', 'Rechtsbewertung'), ('dpia', 'DSFA'), ('audit', 'Audit'), ('document', 'Dokument'), ('report', 'Report'), ('request', 'Anfrage'), ('manual', 'Manuell'), ('processor', 'Auftragsverarbeiter')], default='processing', max_length=20),
        ),
    ]
