# Generated by Django 5.2.12 on 2026-03-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('part_of_group', models.BooleanField(default=False)),
                ('group_details', models.TextField(blank=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_temporary_workers', models.BooleanField(default=False)),
                ('uses_freelancers', models.BooleanField(default=False)),
                ('internal_reporting_channel', models.BooleanField(default=False, help_text='Interner Meldekanal / Hinweisgebersystem vorhanden')),
                ('manages_patents', models.BooleanField(default=False)),
                ('manages_licenses', models.BooleanField(default=False)),
                ('ai_context_notes', models.TextField(blank=True, help_text='Freitext für mandantenspezifische Besonderheiten, die später von der KI berücksichtigt werden dürfen.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Unternehmensprofil',
                'verbose_name_plural': 'Unternehmensprofile',
                'ordering': ['company_name'],
            },
        ),
    ]
