# Generated by Django 5.2.12 on 2026-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='greeting_mode',
            field=models.CharField(choices=[('first_name', 'Vorname'), ('last_name', 'Nachname')], default='last_name', max_length=20, verbose_name='Begrüßungsart'),
        ),
        migrations.AddField(
            model_name='user',
            name='salutation',
            field=models.CharField(choices=[('mr', 'Herr'), ('ms', 'Frau'), ('neutral', 'Neutral')], default='neutral', max_length=20, verbose_name='Anrede'),
        ),
    ]
