# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contractual', 'Vertragslage'), ('tom', 'TOM'), ('subprocessors', 'Unterauftragsverarbeiter'), ('privacy_organisation', 'Datenschutzorganisation'), ('third_country', 'Drittlandtransfer'), ('evidence', 'Nachweise')], max_length=50)),
                ('question_text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_year', models.PositiveIntegerField()),
                ('audit_type', models.CharField(choices=[('annual', 'Jahresaudit'), ('event_based', 'Anlassprüfung'), ('follow_up', 'Nachprüfung')], max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('requested', 'Angefordert'), ('in_progress', 'In Bearbeitung'), ('evaluated', 'Bewertet'), ('completed', 'Abgeschlossen')], default='planned', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=255)),
                ('overall_result', models.CharField(blank=True, choices=[('no_findings', 'Unauffällig'), ('findings', 'Mit Feststellungen'), ('critical', 'Kritisch')], max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='processors.processor')),
            ],
            options={
                'ordering': ['-audit_year', 'processor__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('fulfilled', 'Erfüllt'), ('partially_fulfilled', 'Teilweise erfüllt'), ('not_fulfilled', 'Nicht erfüllt'), ('not_applicable', 'Nicht anwendbar')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('evidence_available', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audits.audit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.auditquestion')),
            ],
            options={
                'ordering': ['question__category', 'question__sort_order', 'question__id'],
            },
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.UniqueConstraint(fields=('processor', 'audit_year', 'audit_type'), name='unique_audit_per_processor_year_type'),
        ),
        migrations.AlterUniqueTogether(
            name='auditresponse',
            unique_together={('audit', 'question')},
        ),
    ]
