# Generated by Django 5.2.12 on 2026-04-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('audits', '0002_audit_tenant_auditresponse_tenant'),
        ('processing', '0013_processingactivity_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audit_year', models.PositiveIntegerField()),
                ('audit_type', models.CharField(choices=[('annual', 'Jährliches Datenschutzaudit'), ('event_based', 'Anlassbezogenes Audit'), ('follow_up', 'Nachaudit / Follow-up')], max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_preparation', 'In Vorbereitung'), ('in_progress', 'In Durchführung'), ('under_review', 'In Prüfung'), ('completed', 'Abgeschlossen')], default='planned', max_length=30)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('execution_type', models.CharField(choices=[('on_site', 'Vor Ort'), ('video', 'Videokonferenz'), ('hybrid', 'Hybrid'), ('remote', 'Remote / Dokumentenprüfung')], default='remote', max_length=30)),
                ('auditor_name', models.CharField(blank=True, max_length=255)),
                ('participants', models.TextField(blank=True, help_text='Teilnehmer des Audits, z. B. Geschäftsführung, DSB, Fachabteilung, IT.')),
                ('summary', models.TextField(blank=True)),
                ('training_recommendations', models.TextField(blank=True)),
                ('overall_result', models.CharField(blank=True, choices=[('no_findings', 'Unauffällig'), ('findings', 'Mit Feststellungen'), ('critical', 'Kritisch')], max_length=30)),
                ('new_procedures_reported', models.BooleanField(default=False, help_text='Wurde im Audit mitgeteilt, dass neue Verfahren hinzugekommen sind?')),
                ('organisational_changes_reported', models.BooleanField(default=False, help_text='Wurden organisatorische oder technische Änderungen gemeldet?')),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_audits', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-audit_year', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('not_checked', 'Noch nicht geprüft'), ('unchanged', 'Unverändert / aktuell'), ('changed', 'Änderungen festgestellt'), ('review_required', 'Neubewertung erforderlich'), ('no_longer_relevant', 'Nicht mehr relevant')], default='not_checked', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('legal_review_required', models.BooleanField(default=False)),
                ('dpia_review_required', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.procedureaudit')),
                ('processing_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_audit_items', to='processing.processingactivity')),
            ],
            options={
                'ordering': ['processing_activity__title', 'processing_activity__id'],
                'unique_together': {('audit', 'processing_activity')},
            },
        ),
    ]
