# Generated by Django 5.2.12 on 2026-04-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('audits', '0003_procedureaudit_procedureaudititem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureaudit',
            name='archived_at',
        ),
        migrations.AlterField(
            model_name='auditresponse',
            name='action_required',
            field=models.BooleanField(default=False, verbose_name='Maßnahme erforderlich'),
        ),
        migrations.AlterField(
            model_name='auditresponse',
            name='evidence_available',
            field=models.BooleanField(default=False, verbose_name='Nachweis vorhanden'),
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='execution_type',
            field=models.CharField(choices=[('on_site', 'Vor Ort'), ('video', 'Videokonferenz'), ('hybrid', 'Hybrid'), ('document_review', 'Dokumentenprüfung')], default='on_site', max_length=30),
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='new_procedures_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='organisational_changes_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='participants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='planned', max_length=30),
        ),
        migrations.AlterField(
            model_name='procedureaudititem',
            name='action_required',
            field=models.BooleanField(default=False, verbose_name='Maßnahme erforderlich'),
        ),
        migrations.AlterField(
            model_name='procedureaudititem',
            name='dpia_review_required',
            field=models.BooleanField(default=False, verbose_name='DSFA prüfen'),
        ),
        migrations.AlterField(
            model_name='procedureaudititem',
            name='legal_review_required',
            field=models.BooleanField(default=False, verbose_name='Rechtsbewertung prüfen'),
        ),
        migrations.AlterField(
            model_name='procedureaudititem',
            name='review_status',
            field=models.CharField(choices=[('not_checked', 'Noch nicht geprüft'), ('unchanged', 'Unverändert'), ('changed', 'Geändert'), ('review_required', 'Weiterer Prüfbedarf'), ('discontinued', 'Nicht mehr genutzt')], default='not_checked', max_length=30),
        ),
        migrations.CreateModel(
            name='ProcedureAuditNewActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung des neuen Verfahrens')),
                ('department_hint', models.CharField(blank=True, max_length=255, verbose_name='Fachbereich / Bereich')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Ansprechpartner')),
                ('description', models.TextField(blank=True, verbose_name='Kurzbeschreibung')),
                ('is_already_active', models.BooleanField(default=False, verbose_name='Bereits produktiv im Einsatz')),
                ('requires_follow_up', models.BooleanField(default=True, verbose_name='Weitere Prüfung / Nachbearbeitung erforderlich')),
                ('notes', models.TextField(blank=True, verbose_name='Weitere Hinweise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_activities', to='audits.procedureaudit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
    ]
