# Generated by Django 5.2.12 on 2026-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_procedureaudit_workflow_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedureaudit',
            old_name='final_closure_recommended_at',
            new_name='preliminary_completed_at',
        ),
        migrations.RemoveField(
            model_name='procedureaudit',
            name='preliminary_report_generated_at',
        ),
        migrations.AlterField(
            model_name='procedureaudit',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('preliminary_completed', 'Vorläufig abgeschlossen'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='planned', max_length=30),
        ),
    ]
