# Generated by Django 5.2.12 on 2026-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_rename_final_closure_recommended_at_procedureaudit_preliminary_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureaudit',
            name='preliminary_open_items_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='procedureaudit',
            name='preliminary_statistics_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
