# Generated by Django 5.2.12 on 2026-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_procedureaudit_preliminary_open_items_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureaudit',
            name='final_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
