# Generated by Django 5.2.12 on 2026-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_procedureaudit_final_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureaudit',
            name='procedure_review_final_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
