# Generated by Django 5.2.12 on 2026-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_procedureaudit_procedure_review_final_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureaudit',
            name='auditor_report_note',
            field=models.TextField(blank=True, verbose_name='Freitext Auditor für Bericht'),
        ),
    ]
