# Generated by Django 5.2.12 on 2026-04-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('audits', '0010_procedureaudit_auditor_report_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureaudit',
            name='checklist_review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedureaudit',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/audits/', verbose_name='Gespeicherte Berichtdatei'),
        ),
        migrations.AddField(
            model_name='procedureaudit',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bericht erzeugt am'),
        ),
        migrations.CreateModel(
            name='ProcedureAuditChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('fulfilled', 'Erfüllt'), ('partially_fulfilled', 'Teilweise erfüllt'), ('not_fulfilled', 'Nicht erfüllt'), ('not_applicable', 'Nicht anwendbar')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('evidence_available', models.BooleanField(default=False, verbose_name='Nachweis vorhanden')),
                ('action_required', models.BooleanField(default=False, verbose_name='Maßnahme erforderlich')),
                ('procedure_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='audits.procedureaudit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.auditquestion')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['question__category', 'question__sort_order', 'question__id'],
                'unique_together': {('procedure_audit', 'question')},
            },
        ),
    ]
