# Generated by Django 5.2.12 on 2026-04-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('audits', '0009_procedureaudit_procedure_review_final_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('preliminary', 'Vorläufig'), ('final', 'Final')], default='preliminary', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('statistics_snapshot', models.JSONField(blank=True, default=dict)),
                ('actions_snapshot', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audits.procedureaudit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
    ]
