# Generated by Django 5.2.12 on 2026-03-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('audits', '0001_initial'),
        ('legal', '0001_initial'),
        ('processing', '0001_initial'),
        ('processors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('av_contract', 'AV-Vertrag'), ('tom', 'TOM'), ('dpia', 'DSFA'), ('audit_form', 'Auditbogen'), ('review_note', 'Prüfvermerk'), ('certificate', 'Zertifikat'), ('consent_text', 'Einwilligungstext'), ('policy', 'Richtlinie'), ('contract', 'Vertrag'), ('other', 'Sonstiges')], max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidentiality_level', models.CharField(choices=[('normal', 'Normal'), ('confidential', 'Vertraulich'), ('strictly_confidential', 'Streng vertraulich')], default='normal', max_length=30)),
                ('related_action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actionitem')),
                ('related_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.audit')),
                ('related_legal_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.legalassessment')),
                ('related_processing_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.processingactivity')),
                ('related_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processors.processor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
