# Generated by Django 5.2.12 on 2026-04-19 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('actions', '0008_actionitem_audit_section'),
        ('audits', '0011_procedureaudit_checklist_review_completed_at_and_more'),
        ('documents', '0002_document_tenant'),
        ('legal', '0008_legalassessment_section_203_process_implemented'),
        ('processing', '0013_processingactivity_archived_at_and_more'),
        ('processors', '0002_alter_processor_options_processor_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='confidentiality_level',
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('general', 'Allgemeines Dokument'), ('av_contract', 'AV-Vertrag'), ('tom', 'TOM'), ('policy', 'Richtlinie'), ('report', 'Bericht'), ('certificate', 'Zertifikat'), ('audit_evidence', 'Audit-Nachweis'), ('other', 'Sonstiges')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='actions.actionitem'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audits.audit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_legal_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='legal.legalassessment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processing_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processing.processingactivity'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processors.processor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Dokumentenordner',
                'verbose_name_plural': 'Dokumentenordner',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder'),
        ),
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_labels', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Dokumentenlabel',
                'verbose_name_plural': 'Dokumentenlabels',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documentlabel'),
        ),
    ]
