# Generated by Django 5.2.12 on 2026-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_catalog_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Katalog-Stand zum Zeitpunkt der Übernahme'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('general', 'Allgemeines Dokument'), ('av_contract', 'AV-Vertrag'), ('tom', 'Technische und organisatorische Maßnahmen'), ('policy', 'Richtlinie'), ('report', 'Bericht'), ('certificate', 'Zertifikat'), ('audit_evidence', 'Audit-Nachweis'), ('other', 'Sonstiges')], default='general', max_length=50),
        ),
    ]
