# Generated by Django 5.2.12 on 2026-04-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('actions', '0009_alter_actionitem_options_and_more'),
        ('audits', '0011_procedureaudit_checklist_review_completed_at_and_more'),
        ('documents', '0004_document_source_catalog_updated_at_and_more'),
        ('legal', '0008_legalassessment_section_203_process_implemented'),
        ('processing', '0013_processingactivity_archived_at_and_more'),
        ('processors', '0004_providercatalogentry_standard_av_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('unedited', 'Unbearbeitet'), ('in_progress', 'In Bearbeitung'), ('final', 'Final')], default='unedited', help_text='Arbeitsstand des Dokuments im Tenant-Kontext.', max_length=20, verbose_name='Bearbeitungsstatus'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Kennzeichnet ein globales Musterdokument, das allen Tenants als Vorlage zur Verfügung steht.', verbose_name='Musterdokument'),
        ),
        migrations.AddField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Upload'), ('template_copy', 'Musterkopie'), ('generated', 'Generiert')], default='upload', max_length=20, verbose_name='Herkunft'),
        ),
        migrations.AddField(
            model_name='document',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='Falls dieses Dokument aus einem Musterdokument kopiert wurde, steht hier die Quelle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='documents.document', verbose_name='Ursprungsmuster'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='actions.actionitem', verbose_name='Zugeordnete Maßnahme'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audits.audit', verbose_name='Zugeordnetes Audit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_legal_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='legal.legalassessment', verbose_name='Zugeordnete Rechtsbewertung'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processing_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processing.processingactivity', verbose_name='Zugeordnetes Verfahren'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processors.processor', verbose_name='Zugeordneter Auftragsverarbeiter'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Bei Musterdokumenten leer lassen. Tenant-Dokumente sind einem Mandanten zugeordnet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.tenant'),
        ),
    ]
