# Generated by Django 5.2.12 on 2026-04-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile'),
        ('actions', '0009_alter_actionitem_options_and_more'),
        ('audits', '0011_procedureaudit_checklist_review_completed_at_and_more'),
        ('documents', '0005_document_document_status_document_is_template_and_more'),
        ('knowledge', '0003_knowledgefolder_analysetext_folder_and_more'),
        ('legal', '0008_legalassessment_section_203_process_implemented'),
        ('processing', '0013_processingactivity_archived_at_and_more'),
        ('processors', '0004_providercatalogentry_standard_av_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='document',
            name='template_source',
        ),
        migrations.AddField(
            model_name='document',
            name='source_text_template',
            field=models.ForeignKey(blank=True, help_text='Falls dieses Dokument aus einem Mustertext kopiert wurde, steht hier die Quelle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_documents', to='knowledge.texttemplate', verbose_name='Quelle Mustertext'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('unedited', 'Unbearbeitet'), ('in_progress', 'In Bearbeitung'), ('final', 'Final')], default='unedited', max_length=20, verbose_name='Bearbeitungsstatus'),
        ),
        migrations.AlterField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Upload'), ('template_copy', 'Kopie aus Mustertext'), ('generated', 'Generiert')], default='upload', max_length=20, verbose_name='Herkunft'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='actions.actionitem'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='audits.audit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_legal_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='legal.legalassessment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processing_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processing.processingactivity'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='processors.processor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.tenant'),
        ),
    ]
