from django.core.management.base import BaseCommand

from processing.models import ProcessingTemplate


class Command(BaseCommand):
    help = "Importiert Standard-Art30-Vorlagen"

    def handle(self, *args, **kwargs):
        templates = [
            # Allgemein
            {
                "title": "Personalverwaltung",
                "template_group": "general",
                "department": "Personal",
                "purpose": "Durchführung des Beschäftigungsverhältnisses",
                "data_subject_categories": "Beschäftigte",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Vertragsdaten, Beschäftigtendaten",
                "retention_period": "Regelmäßig bis 3 Jahre nach Beendigung des Beschäftigungsverhältnisses",
                "tom_summary": "Zugriffsbeschränkung, Rollen- und Berechtigungskonzept, Protokollierung",
            },
            {
                "title": "Lohn- und Gehaltsabrechnung",
                "template_group": "general",
                "department": "Personal",
                "purpose": "Durchführung der Lohn- und Gehaltsabrechnung",
                "data_subject_categories": "Beschäftigte",
                "personal_data_categories": "Gehaltsdaten, Steuerdaten, Sozialversicherungsdaten, Bankdaten",
                "recipients": "Steuerberater, Sozialversicherungsträger, Finanzamt",
                "retention_period": "10 Jahre",
                "tom_summary": "Zugriffsbeschränkung, Verschlüsselung, Protokollierung",
            },
            {
                "title": "Bewerbermanagement",
                "template_group": "general",
                "department": "Personal",
                "purpose": "Durchführung von Bewerbungsverfahren",
                "data_subject_categories": "Bewerber",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Bewerbungsunterlagen, Qualifikationen",
                "retention_period": "6 Monate nach Abschluss des Bewerbungsverfahrens",
                "tom_summary": "Zugriffsbeschränkung, Rollenmodell, Löschkonzept",
            },
            {
                "title": "Kundenverwaltung",
                "template_group": "general",
                "department": "Vertrieb",
                "purpose": "Vertragsanbahnung, Vertragsabwicklung und Kundenbetreuung",
                "data_subject_categories": "Kunden, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Vertragsdaten, Kommunikationsdaten",
                "retention_period": "10 Jahre",
                "tom_summary": "Berechtigungskonzept, Datensicherung, Protokollierung",
            },
            {
                "title": "Marketing",
                "template_group": "general",
                "department": "Marketing",
                "purpose": "Planung und Durchführung von Marketingmaßnahmen",
                "data_subject_categories": "Interessenten, Kunden, Ansprechpartner",
                "personal_data_categories": "Kontaktdaten, Kommunikationsdaten, Nutzungsdaten",
                "retention_period": "Bis Widerruf bzw. Wegfall des Zwecks",
                "tom_summary": "Einwilligungsmanagement, Berechtigungskonzept, Protokollierung",
            },
            {
                "title": "Websitebetrieb",
                "template_group": "general",
                "department": "IT / Marketing",
                "purpose": "Bereitstellung und Betrieb der Unternehmenswebsite",
                "data_subject_categories": "Websitebesucher",
                "personal_data_categories": "IP-Adresse, Logdaten, Nutzungsdaten, Kontaktdaten",
                "retention_period": "Nach Log- und Löschkonzept",
                "tom_summary": "Hosting-Sicherheit, Protokollierung, Zugriffsschutz",
            },
            {
                "title": "Online-Shop",
                "template_group": "general",
                "department": "Vertrieb",
                "purpose": "Abwicklung von Onlinebestellungen",
                "data_subject_categories": "Kunden",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Bestelldaten, Zahlungsdaten",
                "recipients": "Zahlungsdienstleister, Versanddienstleister",
                "retention_period": "10 Jahre für steuerlich relevante Unterlagen",
                "tom_summary": "TLS-Verschlüsselung, Berechtigungskonzept, Backup",
            },
            {
                "title": "Versicherungsverwaltung",
                "template_group": "general",
                "department": "Verwaltung / Finanzen",
                "purpose": "Verwaltung von Versicherungsverträgen und Schadensfällen",
                "data_subject_categories": "Beschäftigte, Kunden, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Vertragsdaten, Schadensdaten, Kontaktdaten",
                "recipients": "Versicherer, Makler, Rechtsberater",
                "retention_period": "Nach Vertrags- und Aufbewahrungsfristen",
                "tom_summary": "Berechtigungskonzept, Zugriffsbeschränkung",
            },
            {
                "title": "Rechtsberater / externe Rechtsvertretung",
                "template_group": "general",
                "department": "Recht / Geschäftsführung",
                "purpose": "Einbindung externer Rechtsberatung und Rechtsvertretung",
                "data_subject_categories": "Mandanten, Beschäftigte, Kunden, Gegner, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Vertragsdaten, Verfahrensdaten",
                "recipients": "Externe Rechtsanwälte, Gerichte, Behörden",
                "retention_period": "Nach Verfahrens- und Aufbewahrungsfristen",
                "tom_summary": "Vertraulichkeit, Zugriffsschutz, sichere Kommunikation",
            },
            {
                "title": "Steuerberater / steuerliche Beratung",
                "template_group": "general",
                "department": "Finanzen",
                "purpose": "Steuerliche Beratung und Erfüllung steuerlicher Pflichten",
                "data_subject_categories": "Beschäftigte, Kunden, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Steuerdaten, Buchhaltungsdaten, Bankdaten",
                "recipients": "Steuerberater, Finanzamt",
                "retention_period": "10 Jahre",
                "tom_summary": "Zugriffsschutz, Datensicherung, Verschlüsselung",
            },
            {
                "title": "Produktion",
                "template_group": "general",
                "department": "Produktion",
                "purpose": "Steuerung und Dokumentation von Produktionsprozessen",
                "data_subject_categories": "Beschäftigte, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Schichtdaten, Protokolldaten",
                "retention_period": "Nach betrieblichem Löschkonzept",
                "tom_summary": "Zugriffsschutz, Protokollierung, Trennung von Rollen",
            },
            {
                "title": "Sicherheitssysteme",
                "template_group": "general",
                "department": "IT / Sicherheit",
                "purpose": "Schutz von Gebäuden, Anlagen und IT-Systemen",
                "data_subject_categories": "Beschäftigte, Besucher, Dienstleister",
                "personal_data_categories": "Zutrittsdaten, Protokolldaten, Videodaten",
                "retention_period": "Nach Sicherheits- und Löschkonzept",
                "tom_summary": "Zugriffsbeschränkung, Verschlüsselung, Protokollierung",
            },
            {
                "title": "Rechtsabteilung",
                "template_group": "general",
                "department": "Recht",
                "purpose": "Bearbeitung rechtlicher Vorgänge und Risiken",
                "data_subject_categories": "Beschäftigte, Kunden, Vertragspartner, Gegner",
                "personal_data_categories": "Stammdaten, Verfahrensdaten, Vertragsdaten, Kommunikationsdaten",
                "retention_period": "Nach Verfahrens- und Aufbewahrungsfristen",
                "tom_summary": "Vertraulichkeit, Zugriffsschutz, sichere Ablage",
            },
            {
                "title": "Vertriebsinnendienst",
                "template_group": "general",
                "department": "Vertrieb",
                "purpose": "Unterstützung von Vertriebsprozessen und Kundenbetreuung",
                "data_subject_categories": "Kunden, Ansprechpartner, Interessenten",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Angebotsdaten, Kommunikationsdaten",
                "retention_period": "Nach Vertrags- und Aufbewahrungsfristen",
                "tom_summary": "Berechtigungskonzept, Datensicherung",
            },
            {
                "title": "Vertriebsaußendienst",
                "template_group": "general",
                "department": "Vertrieb",
                "purpose": "Kundentermine, Vertriebssteuerung und Außendienstorganisation",
                "data_subject_categories": "Kunden, Interessenten, Ansprechpartner, Beschäftigte",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Termin- und Kommunikationsdaten, Standortdaten",
                "retention_period": "Nach Vertrags- und Aufbewahrungsfristen",
                "tom_summary": "Mobile Sicherheit, Geräteverschlüsselung, Zugriffsschutz",
            },
            {
                "title": "Geräteverwaltung",
                "template_group": "general",
                "department": "IT",
                "purpose": "Verwaltung von Endgeräten und IT-Ressourcen",
                "data_subject_categories": "Beschäftigte",
                "personal_data_categories": "Benutzerdaten, Gerätedaten, Zuordnungsdaten, Protokolldaten",
                "retention_period": "Nach Geräte- und Löschkonzept",
                "tom_summary": "Inventarisierung, Zugriffsschutz, Protokollierung",
            },
            {
                "title": "Softwareverwaltung",
                "template_group": "general",
                "department": "IT",
                "purpose": "Verwaltung eingesetzter Software und Lizenzen",
                "data_subject_categories": "Beschäftigte, Ansprechpartner",
                "personal_data_categories": "Benutzerdaten, Lizenzdaten, Nutzungsdaten, Protokolldaten",
                "retention_period": "Nach Vertrags- und Löschkonzept",
                "tom_summary": "Berechtigungskonzept, Lizenzkontrolle, Protokollierung",
            },
            {
                "title": "KI-Services",
                "template_group": "general",
                "department": "IT / Fachbereich",
                "purpose": "Unterstützung fachlicher Prozesse durch KI-gestützte Systeme",
                "data_subject_categories": "Beschäftigte, Kunden, Interessenten, Ansprechpartner",
                "personal_data_categories": "Eingabedaten aus Fachprozessen, Kommunikationsdaten, Protokolldaten",
                "retention_period": "Nach Fach- und Löschkonzept",
                "tom_summary": "Prompt-Governance, Zugriffsschutz, Protokollierung, Datenminimierung",
            },
            {
                "title": "Einkauf / Beschaffung",
                "template_group": "general",
                "department": "Einkauf",
                "purpose": "Beschaffung von Waren und Dienstleistungen",
                "data_subject_categories": "Lieferanten, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Vertragsdaten, Kommunikationsdaten",
                "retention_period": "Nach Vertrags- und Aufbewahrungsfristen",
                "tom_summary": "Berechtigungskonzept, Datensicherung",
            },
            {
                "title": "Fuhrparkverwaltung",
                "template_group": "general",
                "department": "Verwaltung",
                "purpose": "Verwaltung von Firmenfahrzeugen und deren Nutzung",
                "data_subject_categories": "Beschäftigte, Dienstleister",
                "personal_data_categories": "Stammdaten, Fahrzeugzuordnung, Nutzungsdaten, Führerscheindaten",
                "retention_period": "Nach betrieblichem Löschkonzept",
                "tom_summary": "Zugriffsschutz, Protokollierung",
            },
            {
                "title": "Hinweisgeberverfahren (HinSchG)",
                "template_group": "general",
                "department": "Compliance",
                "purpose": "Entgegennahme, Prüfung und Bearbeitung von Hinweisgebermeldungen",
                "data_subject_categories": "Hinweisgeber, beschuldigte Personen, beteiligte Beschäftigte",
                "personal_data_categories": "Sachverhaltsdaten, Kontaktdaten, Verfahrensdaten, Kommunikationsdaten",
                "retention_period": "3 Jahre nach Abschluss des Verfahrens",
                "tom_summary": "Strikte Zugriffsbeschränkung, Vertraulichkeit, getrennte Ablage, Protokollierung",
            },

            # Arztpraxis
            {
                "title": "Patientenverwaltung",
                "template_group": "medical",
                "department": "Praxis",
                "purpose": "Verwaltung von Patientenstammdaten und Behandlungsbeziehungen",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Versicherungsdaten, Behandlungsdaten",
                "retention_period": "Nach medizin- und berufsrechtlichen Aufbewahrungspflichten",
                "tom_summary": "Strenge Zugriffssteuerung, Vertraulichkeit, Protokollierung",
            },
            {
                "title": "Terminverwaltung Arztpraxis",
                "template_group": "medical",
                "department": "Praxis",
                "purpose": "Planung und Koordination von Behandlungsterminen",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Termindaten",
                "retention_period": "Nach Praxis- und Löschkonzept",
                "tom_summary": "Zugriffssteuerung, Rollenmodell",
            },
            {
                "title": "Behandlungsdokumentation",
                "template_group": "medical",
                "department": "Praxis",
                "purpose": "Dokumentation medizinischer Behandlungen",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Gesundheitsdaten, Befunde, Diagnosen, Therapiedaten",
                "retention_period": "Mindestens 10 Jahre, ggf. länger nach Spezialrecht",
                "tom_summary": "Besonders geschützte Gesundheitsdaten, Zugriffsbeschränkung, Protokollierung",
            },
            {
                "title": "Abrechnung Arztpraxis",
                "template_group": "medical",
                "department": "Praxis / Abrechnung",
                "purpose": "Abrechnung ärztlicher Leistungen",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Stammdaten, Versicherungsdaten, Leistungsdaten, Gesundheitsdaten",
                "recipients": "Krankenkassen, KVen, Abrechnungsdienstleister",
                "retention_period": "Nach Abrechnungs- und Aufbewahrungspflichten",
                "tom_summary": "Vertraulichkeit, Zugriffsschutz, sichere Übermittlung",
            },
            {
                "title": "Labor- und Befundkommunikation",
                "template_group": "medical",
                "department": "Praxis",
                "purpose": "Austausch medizinischer Befunde und Laborwerte",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Gesundheitsdaten, Untersuchungsdaten, Kontaktdaten",
                "recipients": "Labore, andere Leistungserbringer",
                "retention_period": "Nach medizinischem Lösch- und Aufbewahrungskonzept",
                "tom_summary": "Sichere Kommunikation, Zugriffsschutz, Protokollierung",
            },
            {
                "title": "Recall- und Erinnerungssystem",
                "template_group": "medical",
                "department": "Praxis",
                "purpose": "Erinnerung an Kontroll- und Vorsorgetermine",
                "data_subject_categories": "Patienten",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Termindaten, ggf. Behandlungsbezug",
                "retention_period": "Nach Zweckfortfall bzw. Widerruf",
                "tom_summary": "Einwilligungsprüfung, sichere Kontaktaufnahme, Zugriffsschutz",
            },

            # Kanzlei
            {
                "title": "Mandatsverwaltung",
                "template_group": "legal",
                "department": "Kanzlei",
                "purpose": "Begründung, Durchführung und Verwaltung von Mandatsverhältnissen",
                "data_subject_categories": "Mandanten, Gegner, Beteiligte, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Mandatsdaten, Verfahrensdaten",
                "retention_period": "Nach berufs- und steuerrechtlichen Aufbewahrungspflichten",
                "tom_summary": "Verschwiegenheit, Zugriffsschutz, sichere Aktenführung",
            },
            {
                "title": "Aktenführung und Dokumentenmanagement Kanzlei",
                "template_group": "legal",
                "department": "Kanzlei",
                "purpose": "Führung elektronischer und physischer Akten",
                "data_subject_categories": "Mandanten, Gegner, Beteiligte, Beschäftigte",
                "personal_data_categories": "Mandatsdaten, Dokumente, Kommunikationsdaten, Verfahrensdaten",
                "retention_period": "Nach berufs- und aufbewahrungsrechtlichen Vorgaben",
                "tom_summary": "Berufsgeheimnis, Zugriffsbeschränkung, Protokollierung",
            },
            {
                "title": "Fristenkontrolle Kanzlei",
                "template_group": "legal",
                "department": "Kanzlei",
                "purpose": "Überwachung gesetzlicher, gerichtlicher und vertraglicher Fristen",
                "data_subject_categories": "Mandanten, Gegner, Beteiligte",
                "personal_data_categories": "Mandatsdaten, Verfahrensdaten, Termindaten",
                "retention_period": "Nach Mandats- und Aufbewahrungspflichten",
                "tom_summary": "Integrität, Protokollierung, rollenbasierter Zugriff",
            },
            {
                "title": "beA- und Gerichts-Kommunikation",
                "template_group": "legal",
                "department": "Kanzlei",
                "purpose": "Elektronische Kommunikation mit Gerichten und Verfahrensbeteiligten",
                "data_subject_categories": "Mandanten, Gegner, Beteiligte, Ansprechpartner",
                "personal_data_categories": "Mandatsdaten, Verfahrensdaten, Kommunikationsdaten",
                "recipients": "Gerichte, Behörden, Verfahrensbeteiligte",
                "retention_period": "Nach Mandats- und Aufbewahrungspflichten",
                "tom_summary": "Sichere Kommunikation, Zugriffsschutz, Protokollierung",
            },
            {
                "title": "Forderungsmanagement Kanzlei",
                "template_group": "legal",
                "department": "Kanzlei / Abrechnung",
                "purpose": "Abrechnung und Beitreibung anwaltlicher Forderungen",
                "data_subject_categories": "Mandanten, Schuldner, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Forderungsdaten, Zahlungsdaten, Verfahrensdaten",
                "retention_period": "Nach steuer- und berufsrechtlichen Aufbewahrungspflichten",
                "tom_summary": "Vertraulichkeit, Zugriffsbeschränkung, sichere Dokumentation",
            },
            {
                "title": "Kanzlei-Abrechnung",
                "template_group": "legal",
                "department": "Kanzlei / Abrechnung",
                "purpose": "Abrechnung anwaltlicher Leistungen",
                "data_subject_categories": "Mandanten, Ansprechpartner",
                "personal_data_categories": "Stammdaten, Kontaktdaten, Leistungsdaten, Zahlungsdaten",
                "retention_period": "10 Jahre",
                "tom_summary": "Zugriffsschutz, Datensicherung, Vertraulichkeit",
            },
        ]

        created_count = 0

        for data in templates:
            _, created = ProcessingTemplate.objects.get_or_create(
                title=data["title"],
                template_group=data["template_group"],
                defaults=data,
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(f"Standardverfahren importiert. Neu angelegt: {created_count}")
        )