# Generated by Django 5.2.12 on 2026-03-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0009_alter_processingactivity_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Verarbeitung für die DSFA')),
                ('necessity_assessment', models.TextField(blank=True, help_text='Bewertung der Notwendigkeit und Verhältnismäßigkeit')),
                ('result_summary', models.TextField(blank=True, help_text='Zusammenfassung der DSFA')),
                ('residual_risk', models.CharField(blank=True, help_text='Restrisiko (niedrig / mittel / hoch)', max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpia', to='processing.processingactivity')),
            ],
        ),
        migrations.CreateModel(
            name='DPIAMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('implemented', models.BooleanField(default=False)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('dpia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='dpia.dpia')),
            ],
        ),
        migrations.CreateModel(
            name='DPIARisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('probability', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=20)),
                ('mitigation_measures', models.TextField(blank=True, help_text='Maßnahmen zur Risikominderung')),
                ('residual_risk', models.CharField(blank=True, help_text='Restrisiko nach Maßnahmen', max_length=50)),
                ('dpia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='dpia.dpia')),
            ],
        ),
    ]
