# Generated by Django 5.2.12 on 2026-03-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0001_initial'),
        ('processing', '0010_remove_processingactivity_dpia_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPIACheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('mandatory', 'Verpflichtend'), ('voluntary', 'Freiwillig')], default='mandatory', max_length=20)),
                ('standard_case', models.CharField(blank=True, choices=[('', 'Kein Standardfall'), ('video', 'Videoüberwachung'), ('gps', 'GPS-Tracking'), ('health', 'Gesundheitsdaten'), ('profiling', 'Profiling / Scoring'), ('employee', 'Beschäftigtenüberwachung')], max_length=50)),
                ('blacklist_relevant', models.BooleanField(default=False)),
                ('systematic_monitoring', models.BooleanField(default=False)),
                ('large_scale_sensitive_data', models.BooleanField(default=False)),
                ('vulnerable_subjects', models.BooleanField(default=False)),
                ('new_technology', models.BooleanField(default=False)),
                ('scoring_or_profiling', models.BooleanField(default=False)),
                ('data_matching', models.BooleanField(default=False)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('open_points', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpia_check', to='processing.processingactivity')),
            ],
        ),
    ]
