# Generated by Django 5.2.12 on 2026-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0002_dpiacheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpiacheck',
            name='blacklist_relevant',
        ),
        migrations.AddField(
            model_name='dpiacheck',
            name='must_list_case',
            field=models.CharField(blank=True, choices=[('', 'Kein Muss-Listen-Fall'), ('biometric_id', 'Biometrische Identifizierung'), ('genetic_data', 'Genetische Daten'), ('health_large_scale', 'Umfangreiche Gesundheitsdaten'), ('video_surveillance', 'Systematische Videoüberwachung'), ('location_tracking', 'Umfangreiches Standort-/Bewegungstracking'), ('profiling_scoring', 'Profiling / Scoring mit erheblicher Wirkung'), ('employee_monitoring', 'Umfangreiche Beschäftigtenüberwachung'), ('data_matching', 'Umfangreiche Datenzusammenführung / Matching'), ('vulnerable_groups', 'Verarbeitung mit besonders schutzbedürftigen Personen'), ('sensitive_large_scale', 'Groß angelegte Verarbeitung sensibler Daten')], max_length=50),
        ),
    ]
