# Generated by Django 5.2.12 on 2026-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0003_remove_dpiacheck_blacklist_relevant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpiacheck',
            name='behaviour_or_performance_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpiacheck',
            name='continuous_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpiacheck',
            name='employee_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpiacheck',
            name='large_scale_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dpiacheck',
            name='public_access_area',
            field=models.BooleanField(default=False),
        ),
    ]
