# Generated by Django 5.2.12 on 2026-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0004_dpiacheck_behaviour_or_performance_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpia',
            options={'ordering': ['processing_activity__title']},
        ),
        migrations.AlterModelOptions(
            name='dpiacheck',
            options={'ordering': ['processing_activity__title']},
        ),
        migrations.AlterModelOptions(
            name='dpiameasure',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='dpiarisk',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='behaviour_or_performance_control',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='continuous_tracking',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='data_matching',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='employee_monitoring',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='large_scale_monitoring',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='large_scale_sensitive_data',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='new_technology',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='public_access_area',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='scoring_or_profiling',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='systematic_monitoring',
        ),
        migrations.RemoveField(
            model_name='dpiacheck',
            name='vulnerable_subjects',
        ),
        migrations.AlterField(
            model_name='dpiacheck',
            name='must_list_case',
            field=models.CharField(blank=True, choices=[('', 'Kein Muss-Listen-Fall'), ('video_surveillance', 'Systematische Videoüberwachung'), ('location_tracking', 'Umfangreiches Standort-/Bewegungstracking'), ('profiling_scoring', 'Profiling / Scoring mit erheblicher Wirkung'), ('employee_monitoring', 'Umfangreiche Beschäftigtenüberwachung'), ('sensitive_large_scale', 'Groß angelegte Verarbeitung sensibler Daten'), ('biometric_id', 'Biometrische Identifizierung'), ('genetic_data', 'Genetische Daten'), ('health_large_scale', 'Umfangreiche Gesundheitsdaten'), ('data_matching', 'Umfangreiche Datenzusammenführung / Matching'), ('vulnerable_groups', 'Verarbeitung mit besonders schutzbedürftigen Personen')], max_length=50),
        ),
    ]
