# Generated by Django 5.2.12 on 2026-03-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0005_alter_dpia_options_alter_dpiacheck_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpiacheck',
            name='standard_case',
        ),
    ]
